name: testmail_reader
description: "A secure test email reader for developers"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP Client
  dio: ^5.4.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # HTML Rendering
  flutter_html: ^3.0.0-beta.2
  
  # Date Formatting
  intl: ^0.19.0
  
  # Share functionality
  share_plus: ^7.2.1
  
  # Google Fonts for developer aesthetic
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  lottie: ^3.3.1
  custom_refresh_indicator: ^4.0.1
  
  # Hive Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/mail.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
